# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Stack Undertow
email: vinney@exnil.io
description: This is a place where Vinney Cavallo writes things about programming and other technical stuff
baseurl: "" # the subpath of your site, e.g. /blog
url: http://vcavallo.github.io
twitter_username: vinneycavallo
github_username:  vcavallo
author: Vinney Cavallo

subtitle: Vinney Cavallo && Doing Things With Data.

show_excerpts: true

header_pages:
  - about.md

disqus:
  shortname: vcavallo-github-io

google_tag: UA-72765315-2

excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
